#!/usr/bin/env bash
# Build a local, commit-addressed release package. CycloneDX identifiers and
# timestamps are generated by Trivy, so its SBOM is intentionally not claimed
# to be byte-for-byte reproducible; the sibling checksum binds this artifact.
set -euo pipefail
umask 022

fail() {
    printf '%s\n' "package build failed: $*" >&2
    exit 1
}

command -v realpath >/dev/null || fail 'realpath is required to validate artifact output paths'
command -v jq >/dev/null || fail 'jq is required to normalize and validate the CycloneDX SBOM'
repo_root=$(git rev-parse --show-toplevel)
repo_root=$(realpath -e -- "$repo_root")
[[ -d "$repo_root" && ! -L "$repo_root" ]] || fail 'repository root is not a real directory'
cd "$repo_root"

if [[ ${SDCMCP_ALLOW_DIRTY:-0} != 1 ]] && [[ -n $(git status --porcelain) ]]; then
    printf '%s\n' 'refusing to package a dirty tree (set SDCMCP_ALLOW_DIRTY=1 for development)' >&2
    exit 1
fi

trivy_version=$(trivy --version | sed -n 's/^Version: //p' | head -n 1)
[[ "$trivy_version" == 0.70.0 ]] || {
    printf '%s\n' "Trivy 0.70.0 is required; found ${trivy_version:-none}" >&2
    exit 1
}

# Extract and validate version from Cargo.toml to prevent silent version staleness.
# The packager and installer both hardcode the version literal, so a bump that updates
# only one would ship a mislabeled package that passes validation. This assertion
# fails loudly if they diverge.
cargo_version=$(awk '
    /^\[workspace\.package\]$/ { in_workspace_package = 1; next }
    /^\[/ { in_workspace_package = 0 }
    in_workspace_package && /^version = / {
        gsub(/"/, "", $3); print $3; exit
    }
' Cargo.toml)
[[ -n $cargo_version ]] || fail 'could not extract version from Cargo.toml [workspace.package]'
[[ $cargo_version == 0.1.0 ]] || fail "version mismatch: Cargo.toml has $cargo_version, packager expects 0.1.0 (update both)"

# Resolve the effective source commit BEFORE deriving package_root and dist_dir.
# When packaging a pre-built binary (SDCMCP_PACKAGE_SKIP_BUILD=1), the caller MUST
# supply the true source commit that built the binary, or the package will be
# uninstallable (install.sh requires a 40-char hex commit in BUILD-INFO).
if [[ ${SDCMCP_PACKAGE_SKIP_BUILD:-0} == 1 ]]; then
    [[ -n ${SDCMCP_BINARY_SOURCE_COMMIT:-} ]] || fail "$(cat <<'EOF'
SDCMCP_PACKAGE_SKIP_BUILD=1 requires SDCMCP_BINARY_SOURCE_COMMIT to be set.
Packaging a pre-built binary without recording its true source commit produces a
package that fails installation with 'BUILD-INFO commit is invalid'.

Obtain the commit from the release image's OCI label or the release tag:
  docker inspect ghcr.io/mechubsec/rustsdcmcp:<version> --format '{{index .Config.Labels "org.opencontainers.image.revision"}}'
or (peel annotated tags to the commit):
  git rev-parse v<version>^{commit}

Then set SDCMCP_BINARY_SOURCE_COMMIT to that commit before packaging.
EOF
)"
    [[ "$SDCMCP_BINARY_SOURCE_COMMIT" =~ ^[0-9a-f]{40}$ ]] \
        || fail 'SDCMCP_BINARY_SOURCE_COMMIT must be a full lowercase Git commit (40 hex chars)'
    # Canonicalize: peel annotated tags to commits so a tag SHA can never be recorded
    git_commit=$(git rev-parse "${SDCMCP_BINARY_SOURCE_COMMIT}^{commit}" 2>/dev/null) || fail "$(cat <<EOF
commit $SDCMCP_BINARY_SOURCE_COMMIT is not present in this clone.
This can happen with unfetched release tags, shallow clones, or commits from a
differently-cloned fork. Fetch the commit first:
  git fetch --tags
or:
  git fetch origin $SDCMCP_BINARY_SOURCE_COMMIT
EOF
)"
    printf '%s\n' "using supplied binary source commit: $git_commit"
else
    git_commit=$(git rev-parse HEAD)
    [[ "$git_commit" =~ ^[0-9a-f]{40}$ ]] || fail 'HEAD must resolve to a full lowercase Git commit'
fi

# The payload (config, installer, mecmcp_ref, SBOM) comes from the working tree.
# Record both the binary's source commit and the payload commit so a reader can see
# when they differ. When skip-build is used from a normal working checkout, the SBOM
# describes the packaging checkout's dependency graph, not the binary's — this is
# honest provenance, and BUILD-INFO records both.
payload_commit=$(git rev-parse HEAD)
[[ "$payload_commit" =~ ^[0-9a-f]{40}$ ]] || fail 'HEAD must resolve to a full lowercase Git commit'

git_sha12=${git_commit:0:12}
source_date_epoch=$(git show -s --format=%ct "$git_commit")
package_date=$(date -u -d "@$source_date_epoch" +%Y%m%d)
package_root="rustsdcmcp_0.1.0.${package_date}.${git_sha12}_amd64"
repo_dist="$repo_root/dist"
if [[ -e "$repo_dist" || -L "$repo_dist" ]]; then
    [[ -d "$repo_dist" && ! -L "$repo_dist" ]] || fail "artifact root is not a real directory: $repo_dist"
else
    mkdir -m 0755 -- "$repo_dist"
fi
repo_dist=$(realpath -e -- "$repo_dist")
[[ "$repo_dist" == "$repo_root/dist" ]] || fail 'artifact root resolves outside the physical repository root'

dist_dir="$repo_dist/$git_commit"
if [[ -e "$dist_dir" || -L "$dist_dir" ]]; then
    [[ -d "$dist_dir" && ! -L "$dist_dir" ]] || fail "commit artifact directory is not a real directory: $dist_dir"
else
    mkdir -m 0755 -- "$dist_dir"
fi
dist_dir=$(realpath -e -- "$dist_dir")
[[ "$dist_dir" == "$repo_dist/$git_commit" && $(dirname -- "$dist_dir") == "$repo_dist" ]] \
    || fail 'commit artifact directory is not the immediate commit child of dist'

archive="$dist_dir/${package_root}.tar.gz"
checksum="${archive}.sha256"
validate_output_entries() {
    local entry type count=0
    declare -A allowed=(
        ["$(basename -- "$archive")"]=1
        ["$(basename -- "$checksum")"]=1
    )
    while IFS=$'\t' read -r entry type; do
        [[ -n "$entry" && "$type" == f && ${allowed[$entry]+yes} ]] \
            || fail "commit artifact directory contains an unsafe or unexpected entry: $dist_dir/$entry"
        [[ ! -L "$dist_dir/$entry" ]] || fail "commit artifact directory contains a symlink: $dist_dir/$entry"
        ((count += 1))
    done < <(find -P "$dist_dir" -mindepth 1 -maxdepth 1 -printf '%f\t%y\n')
    if [[ ${1:-allow-stale} == exact ]]; then
        [[ $count -eq 2 && -f "$archive" && ! -L "$archive" && -f "$checksum" && ! -L "$checksum" ]] \
            || fail "commit artifact directory must contain exactly the archive and checksum (DOT after version): $dist_dir"
    fi
}
validate_output_entries

rm -f -- "$archive" "$checksum"
artifact_complete=0
build_dir=
cleanup() {
    if [[ -n "$build_dir" ]]; then
        rm -rf -- "$build_dir"
    fi
    if [[ $artifact_complete != 1 ]]; then
        rm -f -- "$archive" "$checksum"
    fi
}

# Build unless the caller supplied a binary. Rebuilding a released version on a
# workstation is usually the wrong thing: glibc is forward-incompatible, so a
# binary linked against a newer glibc than the target container will not start
# there — and it fails at service start, after the old binary has been replaced.
# Packaging a release therefore means packaging the binary CI built, extracted
# from the release image, which this flag allows.
#
# rust-junosmcp spells the same thing JMCP_PACKAGE_SKIP_BUILD=1.
if [[ ${SDCMCP_PACKAGE_SKIP_BUILD:-0} == 1 ]]; then
    [[ -x target/release/rustsdcmcp ]] || {
        printf '%s\n' \
            'SDCMCP_PACKAGE_SKIP_BUILD=1 but target/release/rustsdcmcp is missing or not executable.' \
            'Place the binary there first, e.g. from the release image:' \
            '  docker create --name sx ghcr.io/mechubsec/rustsdcmcp:<version>' \
            '  docker cp sx:/usr/local/bin/rustsdcmcp target/release/rustsdcmcp' \
            '  docker rm sx' >&2
        exit 1
    }
    printf '%s\n' 'skipping cargo build: packaging the existing target/release/rustsdcmcp'
else
    cargo build --release -p rustsdcmcp --locked
fi

build_dir=$(mktemp -d)
trap cleanup EXIT
stage_dir="$build_dir/$package_root"
mkdir -p "$stage_dir/bin" "$stage_dir/config" "$stage_dir/packaging/lxc" \
    "$stage_dir/packaging/systemd" "$stage_dir/docs"

install -m 0755 target/release/rustsdcmcp "$stage_dir/bin/rustsdcmcp"
# The source example is intentionally retained unchanged; the package carries
# the package-specific state location consumed by its installed service.
sed 's#/var/lib/sdcmcp/changeset-state.json#/var/lib/rustsdcmcp/changeset-state.json#' \
    examples/sdc.example.json >"$stage_dir/config/sdc.json.example"
install -m 0755 packaging/lxc/install.sh "$stage_dir/packaging/lxc/install.sh"
install -m 0644 packaging/systemd/rustsdcmcp.service "$stage_dir/packaging/systemd/rustsdcmcp.service"
install -m 0644 packaging/systemd/rustsdcmcp.sysusers "$stage_dir/packaging/systemd/rustsdcmcp.sysusers"
install -m 0644 packaging/systemd/rustsdcmcp.tmpfiles "$stage_dir/packaging/systemd/rustsdcmcp.tmpfiles"
# `docs/operations.md` links to this from inside the archive, so a tarball
# without it ships a dead link at the one place an operator is told to look.
install -m 0644 packaging/systemd/rustsdcmcp-tunnel.service.example "$stage_dir/packaging/systemd/rustsdcmcp-tunnel.service.example"
install -m 0644 LICENSE SECURITY.md "$stage_dir/"
install -m 0644 docs/operations.md "$stage_dir/docs/operations.md"

glibc_floor=$(objdump -T "$stage_dir/bin/rustsdcmcp" \
    | { grep -oE 'GLIBC_[0-9]+(\.[0-9]+)+' || true; } \
    | sed 's/GLIBC_//' | sort -Vu | tail -n 1)
[[ -n "$glibc_floor" ]] || {
    printf '%s\n' 'could not determine GLIBC floor' >&2
    exit 1
}

# Under skip-build, the local rustc -vV would record the workstation's toolchain
# for a binary it did not compile — the same false provenance just fixed for commit.
# Extract the authoritative toolchain from rust-toolchain.toml at the effective
# source commit instead.
if [[ ${SDCMCP_PACKAGE_SKIP_BUILD:-0} == 1 ]]; then
    toolchain_channel=$(git show "${git_commit}:rust-toolchain.toml" 2>/dev/null \
        | awk -F= '/^[[:space:]]*channel[[:space:]]*=/ {
            gsub(/^[[:space:]]*|[[:space:]]*$|"/, "", $2); print $2; exit
        }')
    [[ -n $toolchain_channel ]] || fail "$(cat <<EOF
could not extract toolchain channel from rust-toolchain.toml at commit $git_commit.
The file may be missing at that commit or the channel field cannot be parsed.
EOF
)"
    # Must start with "unknown" -- the shared mecmcp packaging-conformance
    # check's R3 clause 3 treats any other prefix as a toolchain claiming to
    # have compiled a binary it did not, regardless of how informative the
    # rest of the string is.
    rustc_metadata="unknown (binary supplied prebuilt via SDCMCP_PACKAGE_SKIP_BUILD; pinned toolchain $toolchain_channel per rust-toolchain.toml at ${git_commit:0:12}; not compiled by this script)"
else
    rustc_metadata=$(rustc -vV | tr '\n' ' ' | sed 's/[[:space:]]*$//')
fi
# Single-sourced from the manifest that actually pins it. Hardcoding this in
# both generated files is how stale package documentation comes back: the next
# mecmcp bump updates one literal and silently leaves the other behind.
#
# Anchored to the mecmcp-* dependency declarations themselves (not just any
# `tag = "..."` in the file) so this keeps working across MEC-14's two pin
# shapes: today's `rev = "<sha>"` while mecmcp-redact is unreleased, and the
# `tag = "vX.Y.Z"` it reverts to once mecmcp-redact ships in a tagged release.
# An unanchored search previously matched a `tag = "v0.24.0"` example inside
# this same file's explanatory comment instead of the actual rev pin below,
# silently mislabeling every package built while the rev pin was in effect.
mapfile -t mecmcp_refs < <(grep -oP '^mecmcp-\S+ = \{.*\b(?:tag|rev) = "\K[^"]+' Cargo.toml | sort -u)
[[ ${#mecmcp_refs[@]} -eq 1 ]] \
    || fail "expected exactly one mecmcp tag/rev pin in Cargo.toml, found: ${mecmcp_refs[*]-none}"
mecmcp_ref=${mecmcp_refs[0]}
binary_sha256=$(sha256sum "$stage_dir/bin/rustsdcmcp" | cut -d' ' -f1)
cat >"$stage_dir/BUILD-INFO" <<EOF
release_status=release
version=0.1.0
git_commit=$git_commit
payload_commit=$payload_commit
source_date_epoch=$source_date_epoch
target=x86_64-unknown-linux-gnu
mecmcp_ref=$mecmcp_ref
glibc_floor=$glibc_floor
rustc=$rustc_metadata
binary_sha256=$binary_sha256
EOF

# The package carries a README describing *itself*, not the repository's,
# which pins whichever version was current when it was written. Copying that
# file shipped every archive with download instructions for the previous
# release. Instructions for obtaining an archive are meaningless inside that
# archive; what a reader here needs is what this is and where to go next.
cat >"$stage_dir/README.md" <<EOF
# rustsdcmcp — package \`$package_root\`

Security Director Cloud MCP server, built from source commit
\`$git_commit\` with the shared \`mecmcp\` crates pinned to
\`$mecmcp_ref\`.

> **Unofficial / community project.** This is an independent community project
> and does not claim affiliation with or endorsement by Hewlett Packard
> Enterprise or Juniper Networks. Product names and trademarks are used only to
> identify the systems with which the software interoperates.

## Prerequisites

- Debian 13 AMD64; an unprivileged LXC is recommended.
- GLIBC $glibc_floor or newer — this binary will not run on an older host.
- 1 vCPU, 512 MiB RAM, 512 MiB swap, 4 GiB disk for the minimum profile.
- Working DNS and time sync, plus outbound HTTPS to
  \`api.sdcloud.juniperclouds.net\`.
- Root or equivalent operator access.

The installer checks only for \`/etc/debian_version\`; it cannot detect an
unsupported release or an insufficient GLIBC. Confirm both before installing.

## Verify before installing

Integrity is established against the archive checksum published beside this
package, **not** from inside it — the \`.sha256\` lives next to the tarball, one
level above this extracted directory.

**Take the checksum from the GitHub release page over an authenticated
connection**, not from whatever channel delivered the archive. A \`.sha256\`
carried alongside the tarball only proves the two files agree; an attacker who
supplied both supplies a matching pair, and the next step runs as root.

If you have not already verified it:

\`\`\`console
(cd .. && sha256sum -c $package_root.tar.gz.sha256)
\`\`\`

Adjust the path if you extracted somewhere other than beside the archive.

**If you extracted before verifying, discard this tree and re-extract.** The
checksum covers the archive, not the files already on disk, so a modified
extraction survives a passing check and would then run as root:

\`\`\`console
cd .. && rm -rf $package_root && tar -xzf $package_root.tar.gz && cd $package_root
\`\`\`

\`BUILD-INFO\` and \`SBOM.cdx.json\` record provenance — source commit,
toolchain, GLIBC floor, dependency set — and are **metadata only**. They confirm
what this package claims to be; they do not detect a modified binary. This one
runs here, in the package root:

\`\`\`console
grep -Fx 'git_commit=$git_commit' BUILD-INFO
\`\`\`

## Install

From this package root, and only after the checksum above verifies:

\`\`\`console
sudo packaging/lxc/install.sh
\`\`\`

The installer never enables the service: configuration and credentials must be
in place first. See \`docs/operations.md\`.

## Contents

| Path | What it is |
|---|---|
| \`bin/rustsdcmcp\` | the server binary |
| \`packaging/lxc/install.sh\` | installer; run as root |
| \`packaging/systemd/\` | unit, sysusers, tmpfiles, tunnel example |
| \`config/sdc.json.example\` | configuration template |
| \`docs/operations.md\` | **start here** — install layout, tokens, egress, deployment |
| \`BUILD-INFO\`, \`SBOM.cdx.json\` | provenance |

## Security model

Credentials come from the environment and never belong in JSON; startup verifies
the credential against \`expected_tenant_id\`; bearer tokens carry exact tool and
tenant scopes; request, response and page sizes are bounded; there is no direct
deploy tool and no unauthenticated write path — mutations require a
two-principal prepare → approve → apply change control.

\`SECURITY.md\` in this directory and \`docs/operations.md\` carry the detail.

## License

MIT — see \`LICENSE\` in this directory.

Full project documentation:
<https://github.com/mechubsec/rustsdcmcp>
EOF
chmod 0644 "$stage_dir/README.md"

# Skip every directory .gitignore already excludes, plus the two places a git
# worktree lands. A nested checkout carries its own Cargo.lock, which Trivy
# reports as a second copy of every dependency -- the SBOM assertions below
# then fail on duplicates that are not in the shipped artifact at all.
trivy filesystem --scanners vuln --format cyclonedx \
    --skip-dirs target,dist,.git,.worktrees,.claude \
    --output "$stage_dir/SBOM.cdx.json" "$repo_root"
sbom_tmp="$stage_dir/SBOM.cdx.json.tmp"
jq '.metadata.component.name = "rustsdcmcp"' "$stage_dir/SBOM.cdx.json" >"$sbom_tmp"
mv -- "$sbom_tmp" "$stage_dir/SBOM.cdx.json"
jq -e '
    .bomFormat == "CycloneDX"
    and (.metadata.component.name == "rustsdcmcp")
    and (.components | type == "array" and length > 0)
    and any(.components[]; .name == "serde")
    and (
        ([
            .components[]
            | select(.name? | strings | startswith("mecmcp-"))
            | [.name, .version]
        ] | sort)
        == [
            ["mecmcp-audit", "0.26.0"],
            ["mecmcp-auth", "0.26.0"],
            ["mecmcp-changeset", "0.26.0"],
            ["mecmcp-redact", "0.26.0"],
            ["mecmcp-runtime", "0.26.0"],
            ["mecmcp-secret", "0.26.0"],
            ["mecmcp-server", "0.26.0"],
            ["mecmcp-transport", "0.26.0"]
        ]
    )
    and (tostring | contains("v0.8.0") | not)
    and (tostring | contains("70ac3d8fb5f27db3257d11aef28bd09587f085e1") | not)
' "$stage_dir/SBOM.cdx.json" >/dev/null || {
    # Only blame a nested checkout when the same name@version actually appears
    # more than once. An oversized set has other causes -- a genuinely new
    # mecmcp crate, or mixed 0.3.6/0.3.7 entries -- and naming the wrong one
    # buries a real provenance failure under a scan-path explanation.
    sbom_dupes=$(jq -r '
        [.components[]? | select(.name? | strings | startswith("mecmcp-"))
            | (.name + "@" + (.version // "unknown"))]
        | group_by(.) | map(select(length > 1)) | flatten | unique | join(", ")
    ' "$stage_dir/SBOM.cdx.json" 2>/dev/null || printf '')
    if [[ -n $sbom_dupes ]]; then
        fail "normalized SBOM lists duplicate mecmcp components ($sbom_dupes); a nested checkout under the repo root was scanned as a second copy"
    fi
    fail 'normalized SBOM lacks required metadata or dependencies'
}
! grep -Fq -- "$repo_root" "$stage_dir/SBOM.cdx.json" \
    || fail 'SBOM contains an absolute repository or worktree path'
chmod 0644 "$stage_dir/SBOM.cdx.json"

(
    cd "$build_dir"
    find "$package_root" -print0 | LC_ALL=C sort -z \
        | tar --create --gzip --file="$archive" --format=posix --sort=name \
            --owner=0 --group=0 --numeric-owner \
            --mtime="@$source_date_epoch" \
            --pax-option=delete=atime,delete=ctime --no-recursion \
            --null --files-from=-
)
(
    cd "$dist_dir"
    sha256sum "$(basename -- "$archive")" >"$(basename -- "$checksum")"
    sha256sum -c "$(basename -- "$checksum")"
)
validate_output_entries exact
packaging/tests/package-smoke.sh "$archive"
# Runs the REAL installer against a staged legacy-only root. Wired here rather
# than left standalone: a regression guard nothing invokes is not a guard.
packaging/tests/test-legacy-store-upgrade.sh "$archive"
artifact_complete=1
printf '%s\n' "built $archive"
